# Generated by Django 4.0.6 on 2022-10-04 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_price_productpropertyvalue_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingoptions',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.shippingoptions'),
        ),
    ]
