# Generated by Django 4.0.6 on 2022-10-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_shippingoptions_name_product_added_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpropertyvalue',
            name='unit',
            field=models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], max_length=5, null=True),
        ),
    ]
