# Generated by Django 4.0.6 on 2022-10-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productpropertyvalue_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpropertyvalue',
            name='name',
        ),
    ]
