# Generated by Django 4.0.6 on 2022-10-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_productpropertyvalue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpropertyvalue',
            name='unit',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
