# Generated by Django 4.0.6 on 2022-10-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_productpropertyvalue_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productproperty',
            name='value',
        ),
        migrations.AlterField(
            model_name='productpropertyvalue',
            name='unit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
