# Generated by Django 4.0.6 on 2022-10-04 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_productproperty_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpropertyvalue',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productproperty'),
        ),
    ]
