# Generated by Django 4.0.6 on 2022-10-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productpropertyvalue_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpropertyvalue',
            old_name='value',
            new_name='property_fk',
        ),
    ]
