# Generated by Django 4.0.6 on 2022-10-04 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_value_productpropertyvalue_property_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproperty',
            name='product_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
    ]
