# Generated by Django 4.0.6 on 2022-10-06 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_discount_discount_percent_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='property_fk',
        ),
        migrations.AddField(
            model_name='productproperty',
            name='product_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.discount'),
        ),
    ]
