# Generated by Django 4.0.6 on 2022-10-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_product_property_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productproperty',
            name='product_fk',
        ),
        migrations.AddField(
            model_name='product',
            name='property_fk',
            field=models.ManyToManyField(blank=True, null=True, to='store.productproperty'),
        ),
    ]
