# Generated by Django 4.0.6 on 2022-10-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='property_fk',
            field=models.ManyToManyField(blank=True, to='store.productproperty'),
        ),
    ]
